/*
    CREATE TABLE
    
    https://www.postgresql.org/docs/current/sql-createtable.html
    
    EXAMPLE:
    
    CREATE [TEMPORARY] [UNLOGGED] TABLE [IF NOT EXISTS] <schema>.tblname
    (
    nameid integer CONSTRAINT PK_tblname PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rowid integer NOT NULL CONSTRAINT FK_tblname_rowid REFERENCES tblothertable(rowid),
    col1 varchar(50) NOT NULL,
    col2 TIMESTAMP(3) NOT null default CURRENT_DATE,
    col3 char(1) not null default 'Y' check(col3 in('Y', 'N', 'U')),
    col4 money NULL,
    col5 decimal(18,2) NULL,
    col6 TEXT NULL
    ) [ON COMMIT DROP];

    CREATE INDEX <schema>.IX_tblname_col1 ON <schema>.tblname (col1);
*/

